const getState =({getstore, getActions, setStore})=>{
    return {
        store:{
            product:[
            {
                id:1,
                title:"",
                image:"https://okinawatonic.co/affiliates/images/three_bottle.png?v=1.15",
                link:"https://7eefcfkxh9wnvsj5kq3hk7dx2d.hop.clickbank.net/"
            },
            {
                id:2,
                title:"",
                image:"https://revenueriver.net/wp-content/uploads/2021/06/res3-300x300.png",
                link:"https://hop.clickbank.net/?cbpage=vsl&affiliate=hjackson56&vendor=restolin"
            },
        
            {
                id:3,
                title:"",
                image:"https://revenueriver.net/wp-content/uploads/2021/06/dex3-300x300.png",
                link:"https://hop.clickbank.net/?cbpage=vsl&affiliate=hjackson56&vendor=dentitox"
            },
            {
                id:4,
                title:"",
                image:"https://revenueriver.net/wp-content/uploads/2021/06/cox1-300x300.png",
                link:"https://hop.clickbank.net/?cbpage=vsl&affiliate=hjackson56&vendor=claritox",
            },
            {
                id:5,
                title:"",
                image:"https://cdn.shopify.com/s/files/1/0324/5142/8489/products/sbp1-min_a14e0916-7a91-4521-9362-c9e4ced62485_720x720.png?v=1609441303",
                link:"https://d6f4e8p7gevd20fp-8oarb2-bk.hop.clickbank.net/"
            },
            {
                id:6,
                title:"",
                image:"https://www.webseeds.com/affiliates/images/1-Bottle-p-500.png",
                link:"https://9e3e78twpa5l2y98ynr94nyo2s.hop.clickbank.net/"
            },
            {
                id:7,
                title:"",
                image:"https://cdn.shopify.com/s/files/1/0062/7035/3521/products/JB_PCF_AMAZON_Bottle_1_110x110@2x.jpg?v=1618264715",
                link:"https://223eb4qzje6i-qixjlllj95s6w.hop.clickbank.net/"
            },
            {
                id:8,
                title:"",
                image:"https://leptitoxaustralia.com/wp-content/uploads/2020/04/resur-1.png",
                link:"https://bf44can2o5wisrifif3chd8p0z.hop.clickbank.net/"
            },
            {
                id:9,
                title:"",
                image:"https://beyond40.com/assets/images/funnels/LB3x-1.png",
                link:"https://d57ca3l4k8udx-h5nnvmgz5i3r.hop.clickbank.net/"
            },
            {
                id:10,
                title:"",
                image:"https://media2.fdncms.com/metrotimes/imager/u/original/27273571/keravita-pro-review-1.png",
                link:"https://5cd9bfw0f71czvg4uiejrebqef.hop.clickbank.net/",
            },
            
               
            ],
            product1:[
                {
                    id:11,
                    title:"",
                    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-0Addk7irTMbYbqngYBHO127mLm-zSyKq3g&usqp=CAU",
                    link:"https://3a5e1gw8lg1curd2nln4figv4r.hop.clickbank.net/"
                },
                {
                    id:12,
                    title:"",
                    image:"https://promindcomplex.com/img/promind1.png",
                    link:"https://dbfa07qyrexitwff4gpds-ezcz.hop.clickbank.net/"
                },
                {
                    id:13,
                    title:"",
                    image:"https://revision20.us/index_files/revision1.png",
                    link:"https://74e94fmvsf3er0blmisrjcxq45.hop.clickbank.net/"
                },
                {
                    id:14,
                    title:"",
                    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0tRRt82IrX8Rt1TeE9bEVaGUQ9aYjkEw9yERl69P7qTL3CczDI52sNevM8Q28A5RDCjXe0PY&usqp=CAc",
                    link:"https://1e3a12l7q5181uf0skva8vfv96.hop.clickbank.net/"
                },
                {
                    id:15,
                    title:"something",
                    image:""
                },
                {
                    id:16,
                    title:"something",
                    image:"http://placehold.jp/150x150.png"
                },
                {
                    id:17,
                    title:"something",
                    image:"http://placehold.jp/150x150.png"
                },
                {
                    id:18,
                    title:"something",
                    image:"http://placehold.jp/150x150.png"
                },
                {
                    id:19,
                    title:"something",
                    image:"http://placehold.jp/150x150.png"
                },
                {
                    id:20,
                    title:"something",
                    image:"http://placehold.jp/150x150.png"
                },
                   
                ],
                product3:[
                    {
                        id:21,
                        title:"something",
                        image:"http://placehold.jp/150x150.png"
                    },
                    {
                        id:22,
                        title:"something",
                        image:"http://placehold.jp/150x150.png"
                    },
                    {
                        id:23,
                        title:"something",
                        image:"http://placehold.jp/150x150.png"
                    },
                    {
                        id:24,
                        title:"something",
                        image:"http://placehold.jp/150x150.png"
                    },
                    {
                        id:25,
                        title:"something",
                        image:"http://placehold.jp/150x150.png"
                    },
                    {
                        id:26,
                        title:"something",
                        image:"http://placehold.jp/150x150.png"
                    },
                    {
                        id:27,
                        title:"something",
                        image:"http://placehold.jp/150x150.png"
                    },
                    {
                        id:28,
                        title:"something",
                        image:"http://placehold.jp/150x150.png"
                    },
                    {
                        id:29,
                        title:"something",
                        image:"http://placehold.jp/150x150.png"
                    },
                    {
                        id:30,
                        title:"something",
                        image:"http://placehold.jp/150x150.png"
                    },
                       
                    ],
                    product4:[
                        {
                            id:31,
                            title:"something",
                            image:"http://placehold.jp/150x150.png"
                        },
                        {
                            id:32,
                            title:"something",
                            image:"http://placehold.jp/150x150.png"
                        },
                        {
                            id:33,
                            title:"something",
                            image:"http://placehold.jp/150x150.png"
                        },
                        {
                            id:34,
                            title:"something",
                            image:"http://placehold.jp/150x150.png"
                        },
                        {
                            id:35,
                            title:"something",
                            image:"http://placehold.jp/150x150.png"
                        },
                        {
                            id:36,
                            title:"something",
                            image:"http://placehold.jp/150x150.png"
                        },
                        {
                            id:37,
                            title:"something",
                            image:"http://placehold.jp/150x150.png"
                        },
                        {  
                            id:38,
                            title:"something",
                            image:"http://placehold.jp/150x150.png"
                        },
                        {
                            id:39,
                            title:"something",
                            image:"http://placehold.jp/150x150.png"
                        },
                        {
                            id:40,
                            title:"something",
                            image:"http://placehold.jp/150x150.png"
                        },

                           
                        ],
                        product5:[
                            {
                                id:41,
                                title:"something",
                                image:"http://placehold.jp/150x150.png"
                            },
                            {
                                id:42,
                                title:"something",
                                image:"http://placehold.jp/150x150.png"
                            },
                            {
                                id:43,
                                title:"something",
                                image:"http://placehold.jp/150x150.png"
                            },
                            {
                                id:44,
                                title:"something",
                                image:"http://placehold.jp/150x150.png"
                            },
                            {
                                id:45,
                                title:"something",
                                image:"http://placehold.jp/150x150.png"
                            },
                            {
                                id:46,
                                title:"something",
                                image:"http://placehold.jp/150x150.png"
                            },
                            {
                                id:47,
                                title:"something",
                                image:"http://placehold.jp/150x150.png"
                            },
                            {
                                id:48,
                                title:"something",
                                image:"http://placehold.jp/150x150.png"
                            },
                            {
                                
                                id:49,
                                title:"something",
                                image:"http://placehold.jp/150x150.png"
                            },
                            {
                                id:50,
                                title:"something",
                                image:"http://placehold.jp/150x150.png"
                            },
                               
                            ],
                            product6:[
                                {
                                    id:51,
                                    title:"something",
                                    image:"http://placehold.jp/150x150.png"
                                },
                                {
                                    id:52,
                                    title:"something",
                                    image:"http://placehold.jp/150x150.png"
                                },
                                {
                                    id:53,
                                    title:"something",
                                    image:"http://placehold.jp/150x150.png"
                                },
                                {
                                    id:54,
                                    title:"something",
                                    image:"http://placehold.jp/150x150.png"
                                },
                                {
                                    id:55,
                                    title:"something",
                                    image:"http://placehold.jp/150x150.png"
                                },
                                {
                                    id:56,
                                    title:"something",
                                    image:"http://placehold.jp/150x150.png"
                                },
                                {
                                    id:57,
                                    title:"something",
                                    image:"http://placehold.jp/150x150.png"
                                },
                                {
                                    id:58,
                                    title:"something",
                                    image:"http://placehold.jp/150x150.png"
                                },
                                {
                                    id:59,
                                    title:"something",
                                    image:"http://placehold.jp/150x150.png"
                                },
                                {
                                    id:60,
                                    title:"something",
                                    image:"http://placehold.jp/150x150.png"
                                },
                                   
                                ],
                                product7:[
                                    {
                                        id:61,
                                        title:"something",
                                        image:"http://placehold.jp/150x150.png"
                                    },
                                    {
                                        id:62,
                                        title:"something",
                                        image:"http://placehold.jp/150x150.png"
                                    },
                                    {
                                        id:63,
                                        title:"something",
                                        image:"http://placehold.jp/150x150.png"
                                    },
                                    {
                                        id:64,
                                        title:"something",
                                        image:"http://placehold.jp/150x150.png"
                                    },
                                    {
                                        id:65,
                                        title:"something",
                                        image:"http://placehold.jp/150x150.png"
                                    },
                                    {
                                        id:66,
                                        title:"something",
                                        image:"http://placehold.jp/150x150.png"
                                    },
                                    {
                                        id:67,
                                        title:"something",
                                        image:"http://placehold.jp/150x150.png"
                                    },
                                    {
                                        id:68,
                                        title:"something",
                                        image:"http://placehold.jp/150x150.png"
                                    },
                                    {
                                        id:69,
                                        title:"something",
                                        image:"http://placehold.jp/150x150.png"
                                    },
                                    {
                                        id:70,
                                        title:"something",
                                        image:"http://placehold.jp/150x150.png"
                                        
                                    },
                                       
                                    ],
                                Health:[
                                        {
                                            id:72,
                                            title:"something",
                                            image:"https://www.lostbookofremedies.com/affiliates/img/new_bor.jpg",
                                            link:""
                                        },
                                        {
                                            id:73,
                                            title:"something",
                                            image:""
                                        },
                                        {
                                            id:74,
                                            title:"something",
                                            image:"http://placehold.jp/150x150.png"
                                        },
                                        {
                                            id:75,
                                            title:"something",
                                            image:"http://placehold.jp/150x150.png"
                                        },
                                        {
                                            id:76,
                                            title:"something",
                                            image:"http://placehold.jp/150x150.png"
                                        },
                                        {
                                            id:77,
                                            title:"something",
                                            image:"http://placehold.jp/150x150.png"
                                        },
                                        {
                                            id:78,
                                            title:"something",
                                            image:"http://placehold.jp/150x150.png"
                                        },
                                        {
                                            id:79,
                                            title:"something",
                                            image:"http://placehold.jp/150x150.png"
                                        },
                                        {
                                            id:80,
                                            title:"something",
                                            image:"http://placehold.jp/150x150.png"
                                        },
                                        {
                                            id:81,
                                            title:"something",
                                            image:"http://placehold.jp/150x150.png"
                                            
                                        },
                                           
                                        ]
    

        },
        actions:{}
    };
};

export default getState ;