const getState =({getstore, getActions, setStore})=>{
    return {
        store:{
            product:[
            {
                id:1,
                title:"",
                image:"https://okinawatonic.co/affiliates/images/three_bottle.png?v=1.15",
                link:"https://7eefcfkxh9wnvsj5kq3hk7dx2d.hop.clickbank.net/"
            },
            {
                id:2,
                title:"",
                image:"https://revenueriver.net/wp-content/uploads/2021/06/res3-300x300.png",
                link:"https://hop.clickbank.net/?cbpage=vsl&affiliate=hjackson56&vendor=restolin"
            },
        
            {
                id:3,
                title:"",
                image:"https://revenueriver.net/wp-content/uploads/2021/06/dex3-300x300.png",
                link:"https://hop.clickbank.net/?cbpage=vsl&affiliate=hjackson56&vendor=dentitox"
            },
            {
                id:4,
                title:"",
                image:"https://revenueriver.net/wp-content/uploads/2021/06/cox1-300x300.png",
                link:"https://hop.clickbank.net/?cbpage=vsl&affiliate=hjackson56&vendor=claritox",
            },
            {
                id:5,
                title:"",
                image:"https://cdn.shopify.com/s/files/1/0324/5142/8489/products/sbp1-min_a14e0916-7a91-4521-9362-c9e4ced62485_720x720.png?v=1609441303",
                link:"https://d6f4e8p7gevd20fp-8oarb2-bk.hop.clickbank.net/"
            },
            {
                id:6,
                title:"",
                image:"https://www.webseeds.com/affiliates/images/1-Bottle-p-500.png",
                link:"https://656c83m4ka-ltziaygg73r992m.hop.clickbank.net/"
            },
            {
                id:7,
                title:"",
                image:"https://cdn.shopify.com/s/files/1/0062/7035/3521/products/JB_PCF_AMAZON_Bottle_1_110x110@2x.jpg?v=1618264715",
                link:"https://223eb4qzje6i-qixjlllj95s6w.hop.clickbank.net/",
            },
            {
                id:8,
                title:"",
                image:"https://leptitoxaustralia.com/wp-content/uploads/2020/04/resur-1.png",
                link:"https://bf44can2o5wisrifif3chd8p0z.hop.clickbank.net/",
            },
            {
                id:9,
                title:"",
                image:"https://beyond40.com/assets/images/funnels/LB3x-1.png",
                link:"https://d57ca3l4k8udx-h5nnvmgz5i3r.hop.clickbank.net/",
            },
            {
                id:10,
                title:"",
                image:"https://media2.fdncms.com/metrotimes/imager/u/original/27273571/keravita-pro-review-1.png",
                link:"https://5cd9bfw0f71czvg4uiejrebqef.hop.clickbank.net/",
            },
            
               
            ],
        product1:[  
                    {
                        id:11,
                        title:"",
                        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-0Addk7irTMbYbqngYBHO127mLm-zSyKq3g&usqp=CAU",
                        link:"https://3a5e1gw8lg1curd2nln4figv4r.hop.clickbank.net/",
                    },
                    {
                        id:12,
                        title:"",
                        image:"https://promindcomplex.com/img/promind1.png",
                        link:"https://dbfa07qyrexitwff4gpds-ezcz.hop.clickbank.net/",
                    },
                    {
                        id:13,
                        title:"",
                        image:"https://revision20.us/index_files/revision1.png",
                        link:"https://74e94fmvsf3er0blmisrjcxq45.hop.clickbank.net/",
                    },
                    {
                        id:14,
                        title:"",
                        image:"https://organichealthremedies.co/affiliates/web/i/product-item-02.jpg",
                        link:"https://1e5e5akym6-czzd-yct02hzo39.hop.clickbank.net/",
                    },
                    {
                        id:15,
                        title:"",
                        image:"https://d2hxwhv2sc3sef.cloudfront.net/go/wp-content/uploads/2015/08/b1.jpg",
                        link:"https://8c060gwwla28uwfkjbnfpx-ebm.hop.clickbank.net/"
                    },
                    {
                        id:16,
                        title:"",
                        image:"https://revitaapro.com/assets/images/starter-pack.png",
                        link:"https://3cf402txg4zktrmeumrpj7rhqi.hop.clickbank.net/"
                    },
                    {
                        id:17,
                        title:"",
                        image:"https://feminineenchantment.com/wp-content/uploads/2020/03/feminine-enchantment-smaller-200x300.jpg",
                        link:"https://65e15en8g6tnu4kij7k9ysdazf.hop.clickbank.net/"
                    },
                    {
                        id:18,
                        title:"",
                        image:"https://www.braintraining4dogs.com/get-btfd/assets/btd-product-sm.png",
                        link:"https://9b2f06l5p82ivthytwll-6yb22.hop.clickbank.net/"
                    },
                    {
                        id:19,
                        title:"",
                        image:"https://quietumplus.com/img/1-bottle.png",
                        link:"https://f9fd49q7qc6br2li76lq-b7cao.hop.clickbank.net/"
                    },
                    {
                        id:20,
                        title:"",
                        image:"https://sqribble.com/cb/new/img/large-img/section-2-lagre-img.png",
                        link:"https://ccad6at7f6zgz3hmvckwiamvan.hop.clickbank.net/",
                    },
                    
                ],
         product2:[
                            {
                                id:21,
                                title:"",
                                image:"https://www.trydivinelocks.com/img/sale/onem-pkg.png",
                                link:"https://7bdf06l4i6wg0zi8am-dsgxtar.hop.clickbank.net/"
                            },
                            {
                                id:22,
                                title:"",
                                image:"https://berenewed.net/non-vsl/images/home_product1.png",
                                link:"https://9a13f6x2fgyn-xmdjkitj70acb.hop.clickbank.net/"
                            },
                            {
                                id:23,
                                title:"",
                                image:"https://ssl.clickbank.net/order/c/painfix/img/hip-flexor-group100.png",
                                link:"https://600008m1i5ynp2fnkbv2xu8u9n.hop.clickbank.net/"
                            },
                            {
                                id:24,
                                title:"",
                                image:"https://nitrilean.com/img/1-bottle.jpg",
                                link:"https://619ffcyxef-azqhinqx9wdoh6k.hop.clickbank.net/"
                            },
                            {
                                id:25,
                                title:"",
                                image:"https://extrasharpear.com/img/ser3-min.png",
                                link:"https://206afbz8ejwfvrh84yuzu46n07.hop.clickbank.net/"
                            },
                            {
                                id:26,
                                title:"",
                                image:"https://hairfortin.net/img/haf3S.png",
                                link:"https://03852ay9ph6jt-ba57-7v2sv85.hop.clickbank.net/"
                            },
                            {
                                id:27,
                                title:"",
                                image:"https://painfree.mindbodymatrix.com/img/1bottle-rock-bottom-fullv3.png",
                        
                                link:"https://77cbeds5dgulsyahclij5f5l4c.hop.clickbank.net/"
                            },
                            {
                                id:28,
                                title:"",
                                image:"https://gforceteeth.com/gfrcb/assets/uploads/GFORCEx1-500px.webp",
                                link:"https://43bec1o5g75gz2fahd25maf83m.hop.clickbank.net/"
                            },
                            {
                                id:29,
                                title:"",
                                image:"https://nervogen.com/img/nep1.png",
                                link:"https://5908bam0ii-l11g7sj9lm-txe7.hop.clickbank.net/"
                            },
                            {
                                id:30,
                                title:"",
                                image:"https://dentivive.com/statics/img/dv-1.png",
                                link:"https://551c15v8ihu8twd6mj18a59aar.hop.clickbank.net/"
                            },
                            
                            ],
                            product3:[
                                {
                                    id:31,
                                    title:"",
                                    image:"https://callofdestiny.org/affiliates/images/Book_3d_s.png",
                                    link:"https://1de3b7sxid-ksrk2p-sm-4vs04.hop.clickbank.net/"
                                },
                                {
                                    id:32,
                                    title:"",
                                    image:"https://tryalive.com/images/demo/img-01.png",
                                    link:"https://ce139do-hevm2sgdwxdbmiqy3t.hop.clickbank.net/"
                                },
                                {
                                    id:33,
                                    title:"",
                                    image:"https://getprimalflow.com/images/primal-flow/pp-flow-6.png",
                                    link:"https://87ba0brvd7t9wtbm6bz00eq85s.hop.clickbank.net/"
                                },
                                {
                                    id:34,
                                    title:"",
                                    image:"https://over30hormonesolution.com/truth/images/o30hs1bottleDesk.jpg",
                                    link:"https://c36de6r6p5w8tsbb5-od5l1s1l.hop.clickbank.net/"
                                },
                                {
                                    id:35,
                                    title:"",
                                    image:"https://www.feelgoodknees.com/hosted/images/f6/8e19c0d3a211e78aa53fa33085996a/Screen-Shot-2017-11-27-at-1.43.42-PM.png",
                                    link:"https://756c53o5q53bp0mo795hudnvae.hop.clickbank.net/"
                                },
                                {
                                    id:36,
                                    title:"",
                                    image:"https://www.meetysweet.com/images/mini-course-pack.png",
                                    link:"https://be2657t9d67nyslfq-8m3q6v0j.hop.clickbank.net/"
                                },
                                {
                                    id:37,
                                    title:"something",
                                    image:"https://deepsleepdiabetesremedy.com/txt-1/images/bonus-1.png",
                                    link:"https://cfdd42x2o4xmpwa04ypydtdydy.hop.clickbank.net/"
                                },
                                {  
                                    id:38,
                                    title:"",
                                    image:"https://muscleimbalancesrevealed.com/wp-content/uploads/2012/04/mirl3-coil-large-corrective-214x300.jpg",
                                    link:"https://1a80f3zzog79wsc9ol0867tn74.hop.clickbank.net/"
                                },
                                {
                                    id:39,
                                    title:"something",
                                    image:"http://placehold.jp/150x150.png"
                                },
                                {
                                    id:40,
                                    title:"something",
                                    image:"http://placehold.jp/150x150.png"
                                },

                                
                                ],
                             
                                 
                                Health:[
                                        {
                                            id:41,
                                            title:"something",
                                            image:"https://www.lostbookofremedies.com/affiliates/img/new_bor.jpg",
                                            link:""
                                        },
                                        {
                                            id:42,
                                            title:"something",
                                            image:""
                                        },
                                        {
                                            id:43,
                                            title:"something",
                                            image:"http://placehold.jp/150x150.png"
                                        },
                                        {
                                            id:44,
                                            title:"something",
                                            image:"http://placehold.jp/150x150.png"
                                        },
                                        {
                                            id:45,
                                            title:"something",
                                            image:"http://placehold.jp/150x150.png"
                                        },
                                        {
                                            id:46,
                                            title:"something",
                                            image:"http://placehold.jp/150x150.png"
                                        },
                                        {
                                            id:47,
                                            title:"something",
                                            image:"http://placehold.jp/150x150.png"
                                        },
                                        {
                                            id:48,
                                            title:"something",
                                            image:"http://placehold.jp/150x150.png"
                                        },
                                        {
                                            id:49,
                                            title:"something",
                                            image:"http://placehold.jp/150x150.png"
                                        },
                                        {
                                            id:50,
                                            title:"something",
                                            image:"http://placehold.jp/150x150.png"
                                            
                                        },
                                           
             ],
             banners:[
                 {
                     id:"51",
                     title:"",
                     image:"https://patriotpoweredspecials.com/hosted/images/8d/07019a04cf4846be1634ae36060064/Trump-2024-Navy-Flag.png",
                     link:"https://bb5b69zyfd3ctsamol2sormz5l.hop.clickbank.net/"
                 },
                 {
                    
                },
                {
                    id:"52",
                    title:"something",
                    image:"https://www.gojctraining.com/hosted/images/1e/68fff096a811e8920f033160fcc497/profit-gen.png",
                    link:"https://555c2gt4sj4ityldcei18z0o0w.hop.clickbank.net/"
                },
                {
                   id:"53",
                   title:"",
                   image:"https://www.powerquadrantsystem.com/hosted/images/01/083dd047dd11e5b194cda4aafc4fc6/power_quadrant_001.png",
                   link:"https://248e77u5nj0e02me0f8l2xbma8.hop.clickbank.net/"
               },
               {
                id:"54",
                title:"",
                image:"https://www.photojobz.com/hosted/images/26/31543e6d3846d9b35eaa0f4ea925a4/banner.ad.250x250.2.png",
                link:"https://027617r4r50czrg1bij-gfyvdu.hop.clickbank.net/"
            },
            {
               id:"55",
               title:"sports betting system",
               image:"https://zcodesystem.com/affiliates2019/images/daily_fantasy_sports.jpg",
               link:"https://ff71c9z4oi7kvxbnikqz5i3x7q.hop.clickbank.net/"
           },
           {
               id:"56",
               title:"when his heart",
               image:"https://womanmenadore.net/images/topnavback.gif",
               link:"https://386fc6t6gfulxwgfo9h2gtau74.hop.clickbank.net/"
           },
           {
              id:"57",
              title:"",
              image:"https://convertri.imgix.net/a5160590-47d8-11ea-99fe-0697e5ca793e/6960678e41396cb444793ca944bbbd16c1840388/bedroomrockstar2020.png?auto=compress,format&fit=scale&w=632&h=382",
              link:"https://b6c6a1l8rhvjy-9zl-myk06fea.hop.clickbank.net/"
          },
          {
            id:"58",
            title:"",
            image:"https://images.clickfunnels.com/22/e50355dd454ac08f1b4eb77788a6d8/CPS_CHAD_MOCKUP_MANGREENS_F-2.png",
            link:"https://8c8642ovgb1eqt7ddcijg7xh2w.hop.clickbank.net/"
        },
        {
           id:"59",
           title:"",
           image:"https://www.cosmicenergybracelet.com/hosted/images/fb/bc9790c82711e78abfd37e76647e5c/bundle-bracelet22.png",
           link:"https://1215f8nvh51eo0c60662dw26hk.hop.clickbank.net/"
       },
       {
           id:"60",
           title:"",
           image:"https://bodyweightburn.com/system/img/bundle_main.jpg",
           link:"https://38639csxsfya-sj053whuw1kac.hop.clickbank.net/"
       },
       {
          id:"61",
          title:"turn 2 bets into a house",
          image:"http://steadysteveo.com/images/header.png",
          link:"https://b9323ez8fhydxsh9p91nhok61j.hop.clickbank.net/"
      },
    
             ]
    

        },
        actions:{

           
           
        }
    };
};

export default getState ;