const getState =({getstore, getActions, setStore})=>{
    return {
        store:{
            product:[
            {
                id:1,
                title:"something",
                image:"http://placehold.jp/150x150.png"
            },
            {
                id:2,
                title:"something",
                image:"http://placehold.jp/150x150.png"
            },
            {
                id:3,
                title:"something",
                image:"http://placehold.jp/150x150.png"
            },
            {
                id:4,
                title:"something",
                image:"http://placehold.jp/150x150.png"
            },
            {
                id:6,
                title:"something",
                image:"http://placehold.jp/150x150.png"
            },
            {
                id:7,
                title:"something",
                image:"http://placehold.jp/150x150.png"
            },
            {
                id:8,
                title:"something",
                image:"http://placehold.jp/150x150.png"
            },
            {
                id:9,
                title:"something",
                image:"http://placehold.jp/150x150.png"
            },
            {
                id:10,
                title:"something",
                image:"http://placehold.jp/150x150.png"
            },
               
            ],
            product1:[
                {
                    id:11,
                    title:"something",
                    image:"http://placehold.jp/150x150.png"
                },
                {
                    id:12,
                    title:"something",
                    image:"http://placehold.jp/150x150.png"
                },
                {
                    id:13,
                    title:"something",
                    image:"http://placehold.jp/150x150.png"
                },
                {
                    id:14,
                    title:"something",
                    image:"http://placehold.jp/150x150.png"
                },
                {
                    id:15,
                    title:"something",
                    image:"http://placehold.jp/150x150.png"
                },
                {
                    id:16,
                    title:"something",
                    image:"http://placehold.jp/150x150.png"
                },
                {
                    id:17,
                    title:"something",
                    image:"http://placehold.jp/150x150.png"
                },
                {
                    id:18,
                    title:"something",
                    image:"http://placehold.jp/150x150.png"
                },
                {
                    id:19,
                    title:"something",
                    image:"http://placehold.jp/150x150.png"
                },
                {
                    id:20,
                    title:"something",
                    image:"http://placehold.jp/150x150.png"
                },
                   
                ],
                product3:[
                    {
                        id:21,
                        title:"something",
                        image:"http://placehold.jp/150x150.png"
                    },
                    {
                        id:22,
                        title:"something",
                        image:"http://placehold.jp/150x150.png"
                    },
                    {
                        id:23,
                        title:"something",
                        image:"http://placehold.jp/150x150.png"
                    },
                    {
                        id:24,
                        title:"something",
                        image:"http://placehold.jp/150x150.png"
                    },
                    {
                        id:25,
                        title:"something",
                        image:"http://placehold.jp/150x150.png"
                    },
                    {
                        id:26,
                        title:"something",
                        image:"http://placehold.jp/150x150.png"
                    },
                    {
                        id:27,
                        title:"something",
                        image:"http://placehold.jp/150x150.png"
                    },
                    {
                        id:28,
                        title:"something",
                        image:"http://placehold.jp/150x150.png"
                    },
                    {
                        id:29,
                        title:"something",
                        image:"http://placehold.jp/150x150.png"
                    },
                    {
                        id:30,
                        title:"something",
                        image:"http://placehold.jp/150x150.png"
                    },
                       
                    ],
                    product4:[
                        {
                            id:31,
                            title:"something",
                            image:"http://placehold.jp/150x150.png"
                        },
                        {
                            id:32,
                            title:"something",
                            image:"http://placehold.jp/150x150.png"
                        },
                        {
                            id:33,
                            title:"something",
                            image:"http://placehold.jp/150x150.png"
                        },
                        {
                            id:34,
                            title:"something",
                            image:"http://placehold.jp/150x150.png"
                        },
                        {
                            id:35,
                            title:"something",
                            image:"http://placehold.jp/150x150.png"
                        },
                        {
                            id:36,
                            title:"something",
                            image:"http://placehold.jp/150x150.png"
                        },
                        {
                            id:37,
                            title:"something",
                            image:"http://placehold.jp/150x150.png"
                        },
                        {  
                            id:38,
                            title:"something",
                            image:"http://placehold.jp/150x150.png"
                        },
                        {
                            id:39,
                            title:"something",
                            image:"http://placehold.jp/150x150.png"
                        },
                        {
                            id:40,
                            title:"something",
                            image:"http://placehold.jp/150x150.png"
                        },

                           
                        ],
                        product5:[
                            {
                                id:41,
                                title:"something",
                                image:"http://placehold.jp/150x150.png"
                            },
                            {
                                id:42,
                                title:"something",
                                image:"http://placehold.jp/150x150.png"
                            },
                            {
                                id:43,
                                title:"something",
                                image:"http://placehold.jp/150x150.png"
                            },
                            {
                                id:44,
                                title:"something",
                                image:"http://placehold.jp/150x150.png"
                            },
                            {
                                id:45,
                                title:"something",
                                image:"http://placehold.jp/150x150.png"
                            },
                            {
                                id:46,
                                title:"something",
                                image:"http://placehold.jp/150x150.png"
                            },
                            {
                                id:47,
                                title:"something",
                                image:"http://placehold.jp/150x150.png"
                            },
                            {
                                id:48,
                                title:"something",
                                image:"http://placehold.jp/150x150.png"
                            },
                            {
                                
                                id:49,
                                title:"something",
                                image:"http://placehold.jp/150x150.png"
                            },
                            {
                                id:50,
                                title:"something",
                                image:"http://placehold.jp/150x150.png"
                            },
                               
                            ],
                            product6:[
                                {
                                    id:51,
                                    title:"something",
                                    image:"http://placehold.jp/150x150.png"
                                },
                                {
                                    id:52,
                                    title:"something",
                                    image:"http://placehold.jp/150x150.png"
                                },
                                {
                                    id:53,
                                    title:"something",
                                    image:"http://placehold.jp/150x150.png"
                                },
                                {
                                    id:54,
                                    title:"something",
                                    image:"http://placehold.jp/150x150.png"
                                },
                                {
                                    id:55,
                                    title:"something",
                                    image:"http://placehold.jp/150x150.png"
                                },
                                {
                                    id:56,
                                    title:"something",
                                    image:"http://placehold.jp/150x150.png"
                                },
                                {
                                    id:57,
                                    title:"something",
                                    image:"http://placehold.jp/150x150.png"
                                },
                                {
                                    id:58,
                                    title:"something",
                                    image:"http://placehold.jp/150x150.png"
                                },
                                {
                                    id:59,
                                    title:"something",
                                    image:"http://placehold.jp/150x150.png"
                                },
                                {
                                    id:60,
                                    title:"something",
                                    image:"http://placehold.jp/150x150.png"
                                },
                                   
                                ],
                                product7:[
                                    {
                                        id:61,
                                        title:"something",
                                        image:"http://placehold.jp/150x150.png"
                                    },
                                    {
                                        id:62,
                                        title:"something",
                                        image:"http://placehold.jp/150x150.png"
                                    },
                                    {
                                        id:63,
                                        title:"something",
                                        image:"http://placehold.jp/150x150.png"
                                    },
                                    {
                                        id:64,
                                        title:"something",
                                        image:"http://placehold.jp/150x150.png"
                                    },
                                    {
                                        id:65,
                                        title:"something",
                                        image:"http://placehold.jp/150x150.png"
                                    },
                                    {
                                        id:66,
                                        title:"something",
                                        image:"http://placehold.jp/150x150.png"
                                    },
                                    {
                                        id:67,
                                        title:"something",
                                        image:"http://placehold.jp/150x150.png"
                                    },
                                    {
                                        id:68,
                                        title:"something",
                                        image:"http://placehold.jp/150x150.png"
                                    },
                                    {
                                        id:69,
                                        title:"something",
                                        image:"http://placehold.jp/150x150.png"
                                    },
                                    {
                                        id:70,
                                        title:"something",
                                        image:"http://placehold.jp/150x150.png"
                                    },
                                       
                                    ]

        },
        actions:{}
    };
};

export default getState ;